### ISSUE TITLE
Visualization of skeleton in demo.ipynb and the re-implementation of RAC in lab4d

### ISSUE THREAD

**Issue by yccyenchicheng** [gengshan-y/rac#1]
Thanks for open-sourcing the code, amazing work!

I have two questions:

- First is related to the visualization in demo.ipynb

I try to view the results across different videos. The reconstructed appearances and shapes look really great. But the skeletons does not seem to be correct, even for the same video shown in the repo:
![Screenshot from 2023-07-06 16-11-06](https://github.com/gengshan-y/rac/assets/27779063/f420f8f5-98ae-4b89-bf4f-5136008dc57a)

How should I fix that?

- Second is regarding the learned bones in your [lab4d re-implementation of RAC](https://lab4d-org.github.io/lab4d/tutorials/category_model.html). Are the bones or joints the same as the original RAC implementation? Or are they implicit representation in lab4d? Is it possible to visualize the bones/joints the similar way shown in demo.ipynb?

Thank you so much.

**Comment by gengshan-y** [comment]
Hi, thanks for your interest. I believe the topology issue is caused by an inconsistent version of networkx package. It should be fixed by 
```pip install networkx==2.5```

The skeleton topology in lab4d is the same as here. We haven't wrote a jupyter notebook, but a visualization script with overlaid skeleton and mesh will come very soon.

**Comment by yccyenchicheng** [comment]
Got it, thanks for the reply! I guess I messed up the environment at some point.

Looking forward to your future release of lab4d!

**Comment by WithFoxSquirrel** [comment]
> Thanks for open-sourcing the code, amazing work!
> 
> I have two questions:
> 
> * First is related to the visualization in demo.ipynb
> 
> I try to view the results across different videos. The reconstructed appearances and shapes look really great. But the skeletons does not seem to be correct, even for the same video shown in the repo: ![Screenshot from 2023-07-06 16-11-06](https://user-images.githubusercontent.com/27779063/251595110-f420f8f5-98ae-4b89-bf4f-5136008dc57a.png)
> 
> How should I fix that?
> 
> * Second is regarding the learned bones in your [lab4d re-implementation of RAC](https://lab4d-org.github.io/lab4d/tutorials/category_model.html). Are the bones or joints the same as the original RAC implementation? Or are they implicit representation in lab4d? Is it possible to visualize the bones/joints the similar way shown in demo.ipynb?
> 
> Thank you so much.

Hi, yccyenchicheng, Can you tell me the system version information of your build environment？
