### ISSUE TITLE
How to Run My Custom Cat Videos in demo.ipynb and Extract Skeletons

### ISSUE THREAD

**Issue by kokist** [gengshan-y/rac#3]
Hi, @gengshan-y !
Thank you for sharing nice work.

I would like to know how to run my custom cat videos in demo.ipynb and extract their skeletons.

Best regards.

**Comment by gengshan-y** [comment]
Hi @kokist thanks for your interest.
RAC builds body models from video collections. The demo is just to visualize the body model fitted to those training videos. It does not support inference on new ones.

One way is to use[DASR](https://github.com/jefftan969/dasr), which distills RAC into a feedforward shape and pose predictor. However, the demo code has not been fully released.

**Comment by kokist** [comment]
@gengshan-y 
Thank you for your response.  

The training code for RAC has been published on the Lab4d side, but is it possible to visualize the results trained with this code in demo.ipynb?
